### ISSUE TITLE
Migrate to yaml from toml

### ISSUE THREAD

**Issue by kyoheiu** [kyoheiu/felix#139]
cf: https://github.com/toml-lang/toml/issues/394

I have the same issue as above - `[exec]` table wrongly contains the next key-value (`syntax-highlighting` in the ongoing branch), and I do not want the *order* of the configuration to mean a lot.
So I think it is reasonable to discard toml and use yaml, which I know has pros and cons though.
At least this app contains the process to initialize the config file (and also the session file) so this migration will cause no big panic.
I keep this issue open a few days, so if you have any idea comment it here.

FYI, the yaml configuration will look like this:
```
# (Optional) Default exec command when open files.
# If not set, will default to $EDITOR.
# default: nvim

# (Optional)
# key (the command you want to use): [values] (extensions)
exec:
  feh:
    [jpg, jpeg, png, gif, svg]
  zathura:
    [pdf]

# (Optional) Whether to use syntax highlighting in the preview mode.
# If not set, will default to false.
syntax_highlight: true

# (Optional) Default theme for syntax highlighting.
# Pick one from the following:
#    Base16OceanDark
#    Base16EightiesDark
#    Base16MochaDark
#    Base16OceanLight
#    InspiredGitHub
#    SolarizedDark
#    SolarizedLight
# If not set, will default to "Base16OceanDark".
default_theme: Base16EightiesDark

# (Optional) Path to .tmtheme file for the syntax highlighting.
# If not set, default_theme will be used.
# theme_path: "/home/kyohei/.config/felix/monokai.tmtheme"

# The foreground color of directory, file and symlink.
# Pick one of the following:
#     Black
#     Red
#     Green
#     Yellow
#     Blue
#     Magenta
#     Cyan
#     White
#     LightBlack
#     LightRed
#     LightGreen
#     LightYellow
#     LightBlue
#     LightMagenta
#     LightCyan
#     LightWhite
#     Rgb(u8, u8, u8)
#     AnsiValue(u8)
# For more details, see https://docs.rs/termion/1.5.6/termion/color/index.html
color:
  dir_fg: LightCyan
  file_fg: LightWhite
  symlink_fg: LightYellow

```
